#!/usr/bin/python3

import minianki

deck = []

def help():
  print("""
    list of commands:

    importing/exporting:
    - import: import cards in import.txt to the main database.
    - init: initialise your deck/synchronise your deck with the main database.
    - save: save your progress/scheduling and cards to the database.

    manage/use deck:
    - browse: browse deck, edit/delete/toggle suspend cards.
    - learn: an anki-esque learning session.
  
    settings and help:
    - exit: end the program.
    - guide: see guides.
    - help: view all commands again.
    - settings: customise deck options.
  """)
  
print("""welcome to minianki!""")
help()

# console-like env
while 1:
  command = input("__________\n>>> ")
  match command:
    case "import":
      minianki.impt()
    case "init":
      minianki.init(deck)
    case "learn":
      minianki.learn(deck)
    case "save":
      minianki.save(deck)
    case "settings":
      minianki.settings()
    case "guide":
      minianki.guide()
    case "browse":
      minianki.browse()
    case "help":
      help()
    case "shua":
      print("hewwo :>")
    case "kiki":
      print("<3")
    case "":
      print("\n")
    case "exit":
      print("thanks for using minianki! bye!")
      break
    case "bye":
      print("see you soon! and thanks for using minianki!")
    case __:
      if command[0] == ":" and "q" in command:
        print("oh my GOD I KNEW IT I KNEW YOU WERE A VIM USER")
        print("but yes bye and thanks for using minianki!")
        break
      else:
        "invalid command. try again!"
