#!/usr/bin/python3

import minianki

deck = []

def help():
  print("""
    minianki v0.2.0
    
    list of commands:

    importing/exporting:
    - import: import cards in import.txt to the main database.

    manage/use deck:
    - browse: see all your cards and edit, suspend or delete them.
    - learn: an anki-esque learning session.
  
    settings and help:
    - exit: end the program.
    - guide: see guides.
    - help: view all commands again.
    - settings: customise deck options.
    
    for any emails or support, please email joshuasoh2008@gmail.com.
  """)
  
print("""welcome to minianki!""")
help()

minianki.init(deck)
minianki.save(deck)

# console-like env
while 1:
  command = input("__________\n>>> ")
  match command:
    case "import":
      minianki.impt(deck)
    case "learn":
      minianki.learn(deck)
    case "browse":
      minianki.browse()
    case "settings":
      minianki.settings()
    case "guide":
      minianki.guide()
    case "help":
      help()
    case "shua":
      print("hewwo :>")
    case "kiki":
      print("<3")
    case "":
      print("\n")
    case "exit":
      print("thanks for using minianki! bye!")
      break
    case "bye":
      print("see you soon! and thanks for using minianki!")
    case __:
      if command[0] == ":" and "q" in command:
        print("oh my GOD I KNEW IT I KNEW YOU WERE A VIM USER")
        print("but yes bye and thanks for using minianki!")
        break
      else:
        "invalid command. try again!"
  minianki.init(deck)
  minianki.save(deck)
